### ISSUE TITLE
Agent Result text(message), python unicode Error

### ISSUE THREAD

**Issue by NELpos** [EmpireProject/Empire#1114] opened 2018-05-11 09:16 UTC
## Empire Version

 [Version] 2.5 

## OS Information (Linux flavor, Python version)
Server : ubuntu, Python 2.7.12
Victim PC : Windows 7 (Use Korean Version)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
[!] Error processing result packet from YFTVNML4 : 'ascii' codec can't encode characters in position 720-721: ordinal not in range(128)

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://user-images.githubusercontent.com/17526600/39916637-017606ca-5546-11e8-99d5-b40500d133a3.png)

## Any additional information

Hi.
I'm using Empire for penetrate testing.

If you look at the above image, the user PC uses unicode in Korean, but the result value after executing the module(like mimikatz or cmd command) to the agent can not be output result  to Unicode, and the error is displayed.

I think I want to be a utf-8 encoding action on the output value, leaving an issue.

Thank you.

**Comment by winnie22** [comment] 2018-05-11 09:25
Hi, @NELpos, could you please test version from dev branch? There is merged PR which solve utf issue (#542 ). It could be similar issue. Thanks!

**Comment by NELpos** [comment] 2018-05-14 02:45
@winnie22 Thank you for answering 

but Same issue occurred

1.  I cloned dev branch git clone -b dev --single-branch https://github.com/EmpireProject/Empire.git
`root@ip-172-31-12-132:~/Empire# git branch -a
* dev
  remotes/origin/dev`
2. I executed "dir" command and same error occured
![image](https://user-images.githubusercontent.com/17526600/39975908-23dd9764-576c-11e8-93ad-bd2548715986.png)

`Empire: H1PSTMLR) > dir
[*] Tasked H1PSTMLR to run TASK_SHELL
[*] Agent H1PSTMLR tasked with task ID 1
(Empire: H1PSTMLR) > [*] Agent H1PSTMLR returned results.
[!] Error processing result packet from H1PSTMLR : 'ascii' codec can't encode characters in position 205-206: ordinal not in range(128)
`

**Comment by winnie22** [comment] 2018-05-14 11:46
Hi @NELpos, I tried to reproduce this error but without success (but I was able find some new issues :)). Could you please start empire with message display enabled (./empire --debug 2), generate again agent stager and try to reproduce this error again? Thanks

**Comment by NELpos** [comment] 2018-05-15 04:46
Hello, @winnie22
This is the debug messages
Please refer to the contents below.
`
(Empire: BHT758RS) > dir
[*] Tasked BHT758RS to run TASK_SHELL
 agents/BHT758RS : {"print": true, "message": "[*] Tasked BHT758RS to run TASK_SHELL"}
[*] Agent BHT758RS tasked with task ID 3
 agents/BHT758RS : {"task": "dir", "event_type": "task", "task_id": 3, "task_name": "TASK_SHELL", "print": true, "message": "[*] Agent BHT758RS tasked with task ID 3"}
 agents/BHT758RS : {"print": false, "message": "[*] Tasked agent to run command dir", "command": "dir"}
(Empire: BHT758RS) >  listeners/http/http : {"print": false, "message": "[*] GET request for 13.125.32.89/login/process.php from 61.43.211.94"}
 listeners/http/http : {"print": false, "message": "[*] GET cookie value from 61.43.211.94 : =UVG+VJscxBU3SpiajOj9msPUxW8="}
 agents/BHT758RS : {"print": false, "message": "[*] handle_agent_data(): sessionID BHT758RS issued a TASKING_REQUEST"}
 listeners/http/http : {"print": false, "message": "[*] Agent from 61.43.211.94 retrieved taskings"}
 listeners/http/http : {"print": false, "message": "[*] POST request data length from 61.43.211.94 : 16734"}
 agents/BHT758RS : {"print": false, "message": "[*] handle_agent_data(): sessionID BHT758RS issued a RESULT_POST"}
 agents/BHT758RS : {"print": false, "message": "[*] Agent BHT758RS got results", "response_name": "TASK_SHELL", "event_type": "result", "task_id": 2}
 agents/BHT758RS : {"print": false, "message": "[*] Agent BHT758RS got results", "response_name": "TASK_SHELL", "event_type": "result", "task_id": 3}
[*] Agent BHT758RS returned results.
 agents/BHT758RS : {"print": true, "message": "[*] Agent BHT758RS returned results."}
[!] Error processing result packet from BHT758RS : 'ascii' codec can't encode characters in position 205-206: ordinal not in range(128)
 agents/BHT758RS : {"print": true, "message": "[!] Error processing result packet from BHT758RS : 'ascii' codec can't encode characters in position 205-206: ordinal not in range(128)"}
`

**Comment by winnie22** [comment] 2018-05-16 07:49
Hi @NELpos, not so much help :). I'll try some more code digging and testing on my lab. Thanks.

**Comment by winnie22** [comment] 2018-05-17 12:48
Hi @NELpos, don't have good news.  As you can see on the following picture, everything works in my lab on Windows K version. :( 
![empire_korean](https://user-images.githubusercontent.com/6103248/40176978-762fead0-59dd-11e8-9d57-87f96def4525.png)

I installed the testing machine in English language and then installed Korean language pack through windows update. Can't reproduce your error. Can you reproduce this error on any other system with Korean language? Is there something special configured?

**Comment by NELpos** [comment] 2018-05-21 06:51
@winnie22 Hi, Thank you for testing 

I think.. My Environment PC is  nothing to speicial configured. (I tested another Windows PC(Korean) and occurred same issue)
+Environment :  Windows7 Professional K Sp1, Korean

So I test for my environment to help you fix issues..
I correct some Agent.py codes and test stdout. (based on dev branch)

First of all, I print "data" variable below reponsePacket loop   
![image](https://user-images.githubusercontent.com/17526600/40293490-1ec066d0-5d0c-11e8-9db0-f2531803178c.png)

 "dir output data", it must be well printing
![image](https://user-images.githubusercontent.com/17526600/40293495-2d756e6e-5d0c-11e8-9f68-b727dd6f13cd.png)

Second of all, I found error occuring line for sqlite result in "data" variable 

If I printed "data" variable , the error is occurred.
![image](https://user-images.githubusercontent.com/17526600/40293653-e4a323ec-5d0c-11e8-8f39-aa46be660b54.png)
![image](https://user-images.githubusercontent.com/17526600/40293631-d2f8b4cc-5d0c-11e8-96ed-0a9de95974de.png)

I also correct some codes to print result row like this(change fetchall, * columns) and print it.
![image](https://user-images.githubusercontent.com/17526600/40293699-195a5d3a-5d0d-11e8-809b-cf26d2d4a9ac.png)

it works well print rows[0] 
![image](https://user-images.githubusercontent.com/17526600/40293734-4233d498-5d0d-11e8-8483-23ac3ba0d5f8.png)

I think sqllite results can be occured encoding issues.
I hope you have a point to solve this problem.

**Comment by winnie22** [comment] 2018-05-23 14:49
Hi, @NELpos, really thanks for this level of details. But, I don't really understand how this is possible :). If I understand your output correctly, Agent return result which is signal at the end of the code segment in agents.py right before return 'VALID' occurs, and then listener should send signal with message Valid results returned. But you don't get there and exception is raised with message Error processing result packet. @xorrior I would really appreciate quick look If you don't mind. Probably missing something here. Thanks!

**Comment by xorrior** [comment] 2018-05-28 13:34
@NELpos I can't seem to reproduce this issue either. I tested on Win 10 x64 w/ Korean language pack installed.

![image](https://user-images.githubusercontent.com/9156069/40616740-14d0e778-625a-11e8-809c-e6cb1df7c267.png)

![image](https://user-images.githubusercontent.com/9156069/40616749-19871cb0-625a-11e8-8da7-24e3eb2e09d8.png)

This error occurs consistently?

**Comment by NELpos** [comment] 2018-05-29 06:47
@xorrior Hi. Ah..  I'll  check some different options between install Korean Windows Image Case and install Korean Pack in English Windows Image Case.

**Comment by xorrior** [comment] 2018-06-05 14:44
@NELpos Any new information? I still can't seem the replicate the issue you were having.

**Comment by Jerry981028** [comment] 2018-06-07 17:01
Windows with Chinese language pack also has the problem. Tried dev branch but didn't solve the problem.

**Comment by NELpos** [comment] 2018-06-11 10:22
@xorrior Hi. I'm sorry to late reply..

I test few computers installed Korean Pack.
I think there's a problem with windows "professional version." 
(professional version don't supply languages change.. I tested all options about languages pack settings.

I tested 3 diffrent Environments per Computer.
1) Windows 7 Ultimake K : works well
2) Windows 7 Professional K : Ascii Error Occured
3) Windows 10 Pro : Ascii Error Occured

Which Windows 10 version did you test?

Or..
If you want to test that issued version, can I help you get the version of the Issue Windows ISO?(Using Google Drive or FTP?)

**Comment by xorrior** [comment] 2018-06-12 23:46
@NELpos I tested using Windows 10 Pro 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/9156069/41322848-3c5cc2c8-6e79-11e8-98e6-c0bdbc9f4b64.png)

**Comment by xorrior** [comment] 2018-06-12 23:52
@Jerry981028 I tested on Win 10, Chinese language pack and the characters aren't represented correctly, but no errors server side :man_shrugging: 
![image](https://user-images.githubusercontent.com/9156069/41322995-fd73617e-6e79-11e8-8368-514e4b3c684d.png)

**Comment by Jerry981028** [comment] 2018-06-13 02:36
I've tested on Windows 10 home Chinese version, Windows 10 Pro, Windows 7 Ultimate, and None of the above works. Always throws the ASCII error.

**Comment by winnie22** [comment] 2018-06-13 11:16
Hi all,
I install windows 10 home in chinese (no language pack after installation) version but still unable to reproduce :(
![empire_chinese](https://user-images.githubusercontent.com/6103248/41347908-598e9a32-6f0b-11e8-8026-7046d554d6ee.png)

This looks like quite strange bug.

**Comment by Jerry981028** [comment] 2018-06-14 03:09
I tested again on windows7 ultimate but with no luck. My installation disk is `cn_windows_7_professional_with_sp1_vl_build_x64_dvd_u_677816.iso`  
![2018-06-14 10-57-47](https://user-images.githubusercontent.com/14978021/41389427-604552d6-6fc3-11e8-83aa-75d71226a84e.png)

**Comment by NELpos** [comment] 2018-06-15 10:47
Hi All.. @xorrior @winnie22 @Jerry981028 

I solved this issue to patch one code line..
`data.encode('ascii', 'ignore')` when responsePackets call self.process_aget_packet method to send data

I do not know if this code patch can affect other well running PCs.
Plz test this code..

*lib/common/Agents.py line : 1657 to 1661*

   for (responseName, totalPacket, packetNum, taskID, length, data) in responsePackets:
         # process the agent's response
          *data = data.encode('ascii', 'ignore')   //this code add*
          self.process_agent_packet(sessionID, responseName, taskID, data)
         results = True

See the image below.

![image](https://user-images.githubusercontent.com/17526600/41464201-66040b60-70d4-11e8-9966-30007318dc11.png)

It works well.

**Comment by Jerry981028** [comment] 2018-06-16 13:10
@NELpos Works well.

**Comment by winnie22** [comment] 2018-06-16 14:17
Hi @NELpos,
sorry, doesn't work for me :(

`(Empire: 7GSMDKA1) > mkdir čřčřšž`
`[*] Tasked 7GSMDKA1 to run TASK_SHELL`
`[*] Agent 7GSMDKA1 tasked with task ID 3`
`(Empire: 7GSMDKA1) > [!] Received error response from 7GSMDKA1`
`[*] Agent 7GSMDKA1 returned results.`
`Mode   Owner                  LastWriteTime        length Name`
`----   -----                  -------------        ------ ----`
`d----- DESKTOP-2O3JQDQ\winnie 6/16/2018 4:10:03 PM`
`invalid type: 39365  `
`[*] Valid results returned by 192.168.101.10`

Can you try this if its work for you? Thx
`data = data.decode('utf8', 'ignore').encode("utf8")`

**Comment by NELpos** [comment] 2018-06-18 01:42
@winnie22 doesn't work for me.
I'll check some error ascii code.

`data.encode('ascii', 'ignore')` 
this code also.. skip the Korean string too It is not perfect way to fix the issue

**Comment by xorrior** [comment] 2018-08-13 01:09
@NELpos I'm going to close this issue for now. There doesn't seem to be any progress on this and I still can't reproduce it.

**Closed by xorrior** 2018-08-13 01:09 UTC
Labels: onhold
