### ISSUE TITLE
Corrupted sessions using outside network routing (NAT)

### ISSUE THREAD

**Issue by Gr3yCod3riX** [EmpireProject/Empire#482] opened 2017-04-09 20:40 UTC
## Empire Version
2.0 beta

## OS Information (Linux flavor, Python version)
debian

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I have conducted following testing:
### **Local testing**
I get an agent session 
-> interact
-> sysinfo (I get information back)
### 
**Public testing using http and http_foreign on VPS (NAT)**
I get an agent session
-> interact
-> sysinfo (nothing happens)
Also I have tried with other commands but it seems like that any session I get is not responsive afterwards

I have tested this couple of times with identical configuration in both scenarios

Is this the issue relating two listeners http and http_foreign?

**Comment by xorrior** [comment] 2017-04-09 21:53
Please see the solution presented in https://github.com/EmpireProject/Empire/issues/363 . Re-open if this is still a problem. Thanks

**Comment by Gr3yCod3riX** [comment] 2017-04-09 21:57
@xorrior  Hi. This is not the same issue. 
In this case like I explained there is a response, and Empire gets a session. The difference is, when it is done over NAT, commands like "sysinfo" and others are not affecting the agent. 

Thank you

**Comment by xorrior** [comment] 2017-04-09 23:21
@Gr3yCod3riX Can you give me some more info on your NAT setup

**Comment by Gr3yCod3riX** [comment] 2017-04-09 23:27
@xorrior 
dns hostname / external port 33999
mapped to:
internal IP / internal port 1100

**Comment by xorrior** [comment] 2017-04-10 00:17
2 things:
I have testing using empire through a NAT setup. The only way it will work with different internal and external ports, is to treat the external host as a re-director. Can you confirm that your empire setup matches what is shown in #363 and then run empire with the --debug 2 flag. Post the output shown when issuing the sysinfo or any other command. You can also remove the -w hidden option in the launcher to show error messages received.

**Comment by Gr3yCod3riX** [comment] 2017-04-10 08:30
It looks like NAT is working. I have used the same setup from #363 with no problems. Now only interaction **after the session** has been established is not working. These are the screenshots with **--debug 2** command.

**### After session negotiation:**
![screenshot_1](https://cloud.githubusercontent.com/assets/13822688/24852535/28db8420-1dd8-11e7-84d7-823d13c412b6.png)

**### Issuing sysinfo command**
![screenshot_2](https://cloud.githubusercontent.com/assets/13822688/24852608/73b7e6aa-1dd8-11e7-81cf-8a0cf78eba68.png)

**### Issuing ps command**
![screenshot_3](https://cloud.githubusercontent.com/assets/13822688/24852642/8faebfa0-1dd8-11e7-9ec9-f038bbddd7c0.png)


Thank you

**Comment by xorrior** [comment] 2017-04-22 01:58
@Gr3yCod3riX I went ahead and tested this setup again. I did not have any issues sending commands and receiving results. I am not able to reproduce this issue. Are you its not possible there is something else preventing agent comms? Otherwise, I unfortunately don't have an answer for you.

**Comment by Gr3yCod3riX** [comment] 2017-04-25 09:11
@xorrior Yes, I will try to test this in some other environment and figure out what should be blocking agent interaction but yet establishing the initial agent session.

**Comment by xorrior** [comment] 2017-04-28 22:08
@Gr3yCod3riX I'm going to close this out for now. Feel free to comment if you have any additional info. I'm sorry that I don't have a solid answer for you at this time.

**Closed by xorrior** 2017-04-28 22:08 UTC
