### ISSUE TITLE
Listener/Launcher not work with public IP

### ISSUE THREAD

**Issue by oscguinea** [EmpireProject/Empire#845] opened 2017-12-01 11:15 UTC
## OS Information (Linux flavor, Python version)
Kali Linux 2017

## Any additional information

I try to connect with my Empire environment since Internet.
I have a port forwarding on my router.

publicIP:publicPort(8082) --> privateIP:privatePort(8082)

I use "listener http" with the following config:

set Port 8082
set Host PublicIP
set BindIP Private IP

Then, I use "launcher powershell" for test but the agent never active to my Empire Environment. 

Telnet since Internet with port 8082 is working
Execute command powershell is not working.

Where is my error?

Thanks

**Comment by xorrior** [comment] 2017-12-05 07:50
duplicate of #825

**Closed by xorrior** 2017-12-05 07:50 UTC
