### ISSUE TITLE
error to generate launcher vbs

### ISSUE THREAD

**Issue by gearcapitan** [EmpireProject/Empire#765] opened 2017-10-19 16:35 UTC
## Empire Version
2.2 

## OS Information (Linux flavor, Python version)

kali 2017.2
## Screenshot of error, embedded text output, or Pastebin link to the error
![sin titulo](https://user-images.githubusercontent.com/13740942/31782758-9a67a27e-b4c1-11e7-9d3b-5c38b1cdb1a6.png)

**Comment by xorrior** [comment] 2017-10-20 05:54
@gearcapitan I'm not sure what happened here. Can you provide more information? What OS Version, Office version, and is this reproducible?

**Comment by gearcapitan** [comment] 2017-10-20 16:03
what happens is that when I try to generate an obfuscated vbs file, this fails when running, so the vbs is generated with errors in its code and can not be executed

**Comment by xorrior** [comment] 2017-10-28 15:25
@gearcapitan looks like the issue is just with the obfuscated version of the launcher. That kind of steps out of my realm of knowledge. @cobbr may be able to provide some assistance but I strongly suggest doing some trouble shooting on your own by changing the obfuscation command and using the Invoke-obfuscation powershell project with a stager string.

**Comment by gearcapitan** [comment] 2017-10-28 18:39
what bothers me, is that previously I could generate this type files without any problem the files objected vbs if they served and now, nobody knows what the developers did that this type of obfuscated files no longer work

**Comment by xorrior** [comment] 2017-10-29 00:53
@gearcapitan I can tell you that I did confirm an issue in Invoke-Obfuscation when using any command with the window style hidden option. Launchers will fail when using that option. This may be the case, but as I said, I would change up the obfuscation command to see if that issue persists here as well. ¯\_(ツ)_/¯

**Comment by cobbr** [comment] 2017-10-30 01:02
I believe the VBScript launcher currently doesn't work w/ obfuscation. Pretty certain that it's because I'm improperly escaping the string containing the launcher coming back from Invoke-Obfuscation, not an issue in Invoke-Obfuscation itself.

String escaping in VBScript is just the worst. Definitely would love some help there if you want @gearcapitan :) If not I'll try to get around to learning how to VBScript when I find time.

**Comment by e0x70i** [comment] 2017-10-30 17:29
Yeah the quotes need to be escaped, you need to add extra quotes to escape the quotes. We've been using a separate script to generate macro files instead of using the built in one and its working with obfuscated payloads . I can take a pass at integrating the escaping logic into Empire sometime this week. Probably just need to throw `for i, s in enumerate(paylist):
        paylist[i] = s.replace('"', '""')`  somewhere in there.

**Comment by cobbr** [comment] 2017-10-31 00:27
@e0x70i That would be awesome! Thanks

**Comment by gearcapitan** [comment] 2017-11-13 03:06
@e0x70i some progress? The bat and vbs files generated by empire still do not work, obvious only those that have the parameter of obfuscated

**Comment by e0x70i** [comment] 2017-11-29 01:08
sorry @gearcapitan  I didn't make the fix, but looks like cobbrs latest pull request has the fixes!

**Comment by xorrior** [comment] 2017-12-04 04:03
Fixed in #826

**Closed by xorrior** 2017-12-04 04:03 UTC
Labels: help wanted
