### ISSUE TITLE
install.sh - ImportError: cannot import name main

### ISSUE THREAD

**Issue by ghost** [EmpireProject/Empire#1117] opened 2018-05-12 15:31 UTC
## Empire Version
2.3.0

## OS Information (Linux flavor, Python version)
Ubuntu 17.10 x86_64
Python 2.7.14
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
1.Upon running install.sh script installs pip-10.0.1 which then causes 
this error: 'ImportError: cannot import name main' which the script then fails to continue the installation
2.I tried installing other pip packages but I still reproduce the same error, 
only fix I was able to do was to reinstall with this command.
sudo python -m pip uninstall pip && sudo apt install python-pip --reinstall
And install the required pip packages via the requirements.txt

## Screenshot of error, embedded text output, or Pastebin link to the error
https://pastebin.com/w6J1SKMY

**Comment by johncole2017** [comment] 2018-05-13 11:42
I think you must execute install.sh with root permission, means run command " sudo ./install.sh"
before that use "sudo install -r requirements.txt" command

**Comment by dangwasec** [comment] 2018-05-13 17:40
Tried doing so before, I was able to produce the same error.
https://github.com/pypa/pip/issues/5240
https://github.com/pypa/pip/issues/5221

Here are some issues that are related to my case.

**Comment by xorrior** [comment] 2018-05-15 04:35
@dangwasec @johncole2017 I'm unable to reproduce the issue you guys are having. Ubuntu 17 and Empire 2.5. I didn't receive any errors when running the install script as root. 

![image](https://user-images.githubusercontent.com/9156069/40036734-1c82be0c-57d7-11e8-8fc9-e05f9994ee0f.png)

Can you guys update to the latest version of Empire and try the installer?

**Comment by xorrior** [comment] 2018-05-15 04:37
hey @dangwasec @johncole2017, I was unable to reproduce this issue on Ubuntu 17 and Empire 2.5/master. Can you try upgrading to the latest version and running the installer again?

![image](https://user-images.githubusercontent.com/9156069/40036883-146c3846-57d8-11e8-868b-c765114f5daa.png)

**Comment by johncole2017** [comment] 2018-05-16 07:42
@xorrior  I don't have issue with this . @dangwasec  has

**Comment by dangwasec** [comment] 2018-05-17 15:47
Will try to reproduce the error. What kind of information do you need? @xorrior

**Comment by xorrior** [comment] 2018-05-22 00:45
@ghost Have you tried updating to the latest version and running the installer as root?

**Comment by xorrior** [comment] 2018-06-01 18:14
Closing this since the account associated with this issue has been deleted.

**Closed by xorrior** 2018-06-01 18:14 UTC
Labels: onhold

**Comment by iNoSec** [comment] 2018-12-24 14:39
the error is due to pip upgrading with version > to 9.x i have same issue multiple times with other python script which upgrade pip before install all it need... to fix this you must sudo rm -vrf /usr/local/lib/python2.7/dist-packages/pip
and after sudo apt install --reinstall python-pip and remove all the upgrade pip in the installation script of empire and launch it again and thtas it
