### ISSUE TITLE
MSbuild doesn't complete Stage 2

### ISSUE THREAD

**Issue by passwordleak** [EmpireProject/Empire#1052] opened 2018-03-29 15:56 UTC
## Empire Version
Master

## OS Information (Linux flavor, Python version)
Kali Server
Windows 10 Client

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Working empire agent after running msbuild launcher.xml

## Screenshot of error, embedded text output, or Pastebin link to the error

(Empire: agents) > [*] Agent D4XWNYRS returned results.
[*] Valid results returned by 192.168.10.126
[*] Sending POWERSHELL stager (stage 1) to 192.168.10.12
[*] New agent RP2Y9CVX checked in
[+] Initial agent RP2Y9CVX from 192.168.10.12 now active (Slack)
[*] Sending agent (stage 2) to RP2Y9CVX at 192.168.10.12

Stops there and the agent loses connection

Unhandled Exception: System.Management.Automation.CmdletInvocationException: Cannot validate argument on parameter 'Seconds'. The -22 argument is less than the minimum allowed range of 0. Supply an argument that is greater than or equal
to 0 and then try the command again. ---> System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'Seconds'. The -22 argument is less than the minimum allowed range of 0. Supply an argument
 that is greater than or equal to 0 and then try the command again. ---> System.Management.Automation.ValidationMetadataException: The -22 argument is less than the minimum allowed range of 0. Supply an argument that is greater than or e
qual to 0 and then try the command again.

## Any additional information
It seems as if exceptions are causing it to crash completely instead of continuing like in powershell. Is there any way to change the automation dll to continue on exceptions?

**Comment by passwordleak** [comment] 2018-03-29 16:13
OK I found it it was because the stager retries was 0. After setting it to like 100, it works.

**Comment by TheKevinWang** [comment] 2018-03-30 13:58
I found that this is caused by the exe crashing when there is an unhandled exception thrown by PowerShell. By default, powershell will ignore errors. This is due to the fact that it uses pipeline.Commands.AddScript(cmd). However, the PowerShell class does not have this problem. The same problem exists in SharpPick. 

Here is the SharpPick modifications I made:
https://github.com/TheKevinWang/SharpPick

I also modified the xml file to use this method:
https://gist.github.com/TheKevinWang/b80eb6430861f0511c71f9d221a8debd

I was able to get the dropbox module to work. However, a lot of modules still don't work in this kind of run environment.

**Comment by xorrior** [comment] 2018-03-31 15:01
@passwordleak I'll take a look at this. I would suggest not using the Dropbox module. I believe they are actively killing connections that look like empire c2 traffic.

**Comment by bkr32** [comment] 2018-04-05 11:57
@xorrior this seems to occur with .vbs as well,
stops after sending stage 2

**Comment by xorrior** [comment] 2018-04-08 16:02
@passwordleak I'm not able reproduce this behavior on a Win10 x86 host. The agent receives and processes commands without issue 

![image](https://user-images.githubusercontent.com/9156069/38469531-493604ec-3b24-11e8-8310-4601e6eb464c.png)

![image](https://user-images.githubusercontent.com/9156069/38469537-5f082b42-3b24-11e8-9ebc-c3af2ff176e6.png)

Are you setting Obfuscate to True when generating the xml?

**Comment by passwordleak** [comment] 2018-04-09 19:36
Are you using the dropbox module? From the screenshot, it seems like you're using the http listener.  I got the http module working just fine, however the dropbox module didn't work. The xml file provided by @TheKevinWang did work for me though. 

I have the Obfuscate set to false.

**Comment by xorrior** [comment] 2018-05-15 00:59
@passwordleak I wasn't able to reproduce the issue you were having with the dropbox listener.

![dropbox](https://user-images.githubusercontent.com/9156069/40030627-91621b78-57b9-11e8-984d-cefd732bd935.png)
![commands](https://user-images.githubusercontent.com/9156069/40030626-9157e716-57b9-11e8-8b31-30ef74519604.png)

**Comment by xorrior** [comment] 2018-05-25 21:11
@passwordleak I'm going to close this out for now. If you are able to reproduce this again, please let me know.

**Closed by xorrior** 2018-05-25 21:11 UTC
Labels: onhold
