### ISSUE TITLE
Empire doestn run any command

### ISSUE THREAD

**Issue by PandoraSec** [EmpireProject/Empire#368] opened 2016-10-13 05:03 UTC
## Empire Version

1.6.0 master and beta
## OS Information (Linux flavor, Python version)

kali linux debian 4.7.5 
python 2.7.12
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

when  get a session of empire doesn't run any command, but only happen when i have an external session, it works with session inside of my lan, the session connect correctly, even the time in the info of the session runs well, just doesnt run commands, even shell, or modules
## Screenshot of error, embedded text output, or Pastebin link to the error

![screenshot from 2016-10-12 23-03-20](https://cloud.githubusercontent.com/assets/22203976/19337202/19c7ad50-90d0-11e6-8e2e-4cccef569243.png)

**Comment by leesoh** [comment] 2016-10-13 13:50
Hey there! Two questions for you:

1. Can you try this again but running empire with the --debug 2 parameter and post the output?
2. Does this happen with the 2.0_beta?

**Comment by PandoraSec** [comment] 2016-10-14 17:48
yes, i do that and doesnt work too :/
and its happening too with the local net

**Comment by HarmJ0y** [comment] 2016-10-24 17:54
"running empire with the --debug 2 parameter and post the output" -> can you please post some of this output? Debug set to 2 outputs the debug to the screen, which will allow us to see if requests are coming in at all, or if something is causing an error in processing.

**Comment by Diiga** [comment] 2016-10-30 23:07
same here ,does anyone have a fix for this ?

**Comment by rvrsh3ll** [comment] 2016-10-30 23:57
@Diiga can you provide any output from --debug 2 set when you run empire?

**Comment by qgrosperrin** [comment] 2016-11-02 14:31
For what it's worth, I had similar errors when tasking agents with various modules and shell commands.

From the debug output (not exactly --debug 2, but all I had), I could see something similar to the following in the empire.debug log when attempting to executing the command 'shell whoami /all':
```
2016-10-28 15:29:12 Agents : [*] Tasked LSKNCBANG4AKRGW3 to run TASK_SHELL
2016-10-28 15:29:13 HttpHandler : [*] /news.asp requested from LSKNCBANG4AKRGW3 at X.X.X.X
[...]
2016-10-28 15:29:42 HttpHandler : [*] /news.asp requested from LSKNCBANG4AKRGW3 at X.X.X.X
[...]
2016-10-28 15:30:09 HttpHandler : [*] /news.asp requested from LSKNCBANG4AKRGW3 at X.X.X.X
```

From the logs you can see __it's still beaconing normally__ for a while after the command is tasked, but it never returns any output. The command used (i.e. whoami) should obviously return quickly, but this behaviour was noted for different commands and modules so not just this one.

In this instance, the output was never returned (I was not getting stderr for anything btw, not sure if that's expected/normal). Waited a few minutes (with the agent still beaconing normally) and tried another command or the same one, then I could get some output back. I'm confident it was not a communication error because of that. And because the command is simple, I would say it wasn't because the command took too long or hung... 

This happened fairly randomly to be honest... For that reason, I can't seem to be able to reproduce this reliably.

**Comment by nixublx** [comment] 2016-11-12 14:15
I experienced a similar issue and traced it back to Empire 1.6 locking up when it is handling a connection that is not properly terminated (e.g. due to 'half-open' scanners). I created this [Multithreading](https://github.com/adaptivethreat/Empire/pull/387) patch in order to handle concurrent clients, which alleviates the problem of 'rogue' agents.

**Comment by atkinsj** [comment] 2016-11-12 14:21
@nixublx while I appreciate you are keen to get your patch accepted, I don't think either of the issues you've commented on are related to your issue. these are very real issues that are present in 2.0 which uses Flask for HTTP.

**Comment by Alcyon** [comment] 2016-11-12 21:56
@atkinsj it seems that @qgrosperrin 's issue is dissimilar since the agent beacons are logged and in my case there was no logging at all. But FWIW @PandoraSec 's setup is exactly the same as mine and problems started appearing with external sessions.

**Comment by syndrowm** [comment] 2016-11-25 20:51
For me, this was a system time issue. The agent code checks for a 12 hour time difference between itself and the server. [here](https://github.com/adaptivethreat/Empire/blob/master/data/agent/agent.ps1#L895)

**Comment by cobbr** [comment] 2016-11-27 01:08
@syndrowm Thank you! A quick ```service ntp restart``` did the trick for me. I also reset empire with ```./setup/reset.sh```, but I'm not sure if that step was necessary.

**Comment by enigma0x3** [comment] 2016-11-30 01:29
@PandoraSec, is there a time delay between the target and the control server?

**Comment by enigma0x3** [comment] 2016-12-31 02:52
@PandoraSec are you able to verify if there is a time delay between the target and the server?

**Comment by xorrior** [comment] 2017-04-02 02:43
@PandoraSec I'm going to close this out since there hasn't been a response from you for the past couple months.

**Closed by xorrior** 2017-04-02 02:43 UTC

**Comment by anadr** [comment] 2017-04-29 02:48
Had this issue tonight, which was resolved by fixing system clock on victim machine (it was one day ahead).

**Comment by kurobeats** [comment] 2017-05-08 02:04
Can I please suggest this issue be reopened? A victim machine with an out of sync system clock is extremely common.

**Comment by anadr** [comment] 2017-05-08 02:24
This is fixed in the beta version (v2) of Empire
