### ISSUE TITLE
TLS Connection Problem When Empire is Located on an External Server

### ISSUE THREAD

**Issue by utkusen** [EmpireProject/Empire#665] opened 2017-08-30 15:19 UTC
## Empire Version
2.1 (30 August 2017)

## OS Information (Linux flavor, Python version)
Ubuntu 16.04, Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Empire is located on a Digitalocean server. It's not behind NAT, local IP is same with external IP. It doesn't have a problem when I use Http for communication. But when I try to use it with Https, it's not working. Victim&Empire communication is not working also when I try to navigate to the listener address, communication times out. Here is my https listener settings:

  ```
KillDate          False                                        Date for the listener to exit (MM/dd/yyyy).
  Name              True        https                            Name for the listener.
  Launcher          True        powershell -noP -sta -w 1 -enc   Launcher string.
  DefaultProfile    True        /admin/get.php,/news.php,/login/ Default communication profile for the agent.
                                process.php|Mozilla/5.0 (Windows
                                NT 6.1; WOW64; Trident/7.0;
                                rv:11.0) like Gecko
  DefaultLostLimit  True        60                               Number of missed checkins before exiting
  DefaultDelay      True        5                                Agent delay/reach back interval (in seconds).
  Host              True        https://x.x.x.x:443      Hostname/IP for staging.
  Port              True        443                              Port for the listener.
  WorkingHours      False                                        Hours for the agent to operate (09:00-17:00).
  CertPath          False       root/Empire/data/                Certificate path for https listeners.
  DefaultJitter     True        0.0                              Jitter in agent reachback interval (0.0-1.0).
  StagingKey        True        >UT(vS[1f05OxnY@&D?pb#r:3.H/j!By Staging key for initial agent negotiation.
  BindIP            True        0.0.0.0                          The IP to bind to on the control server.
  ServerVersion     True        Microsoft-IIS/7.5                Server header for the control server.
```
This is the traffic capture from victim machine (multi/launcher is used): https://imgur.com/a/ekusW

**Comment by xorrior** [comment] 2017-08-30 21:07
This is a duplicate of #643

**Closed by xorrior** 2017-08-30 21:07 UTC
