### ISSUE TITLE
OBFUSCATED stager doesn't start (Cannot convert value ...)

### ISSUE THREAD

**Issue by paleos** [EmpireProject/Empire#682] opened 2017-09-07 16:38 UTC
## Empire Version
Empire 2 / DEV branch (20170906 version)

## OS Information (Linux flavor, Python version)
Server - Linux/KALI2
Client - Win7 Pro, 64bit

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Obfuscated stager (windows/launcher_bat) doesn't start. There is error (see bellow)

## Screenshot of error, embedded text output, or Pastebin link to the error
ERROR (when starting obfuscated code in command prompt):
Processing -WindowStyle 'hIDDE' failed: Cannot convert value "hIDDE" to type "System.Diagnostics.ProcessWindowStyle" due to invalid enumeration values. Specify one of the following numeration values and try again. The possible enumeration values are "Normal, Hidden, Minimized, Maximized".

## Any additional information
Non-obfuscated stager/listener works but it is catched by Symantec when BAT file is downloaded to filesystem.

**Comment by PoSHMagiC0de** [comment] 2017-09-09 17:46
I am getting a different error.

[!] Exception: obfuscate() got multiple values for keyword argument 'obfuscationCommand'

When trying to generate stager.

**Comment by nkokhi** [comment] 2017-09-26 14:30
I am having same issue as @PoSHMagiC0de

**Comment by alex-bergman** [comment] 2017-09-29 06:33
[!] Exception: obfuscate() got multiple values for keyword argument 'obfuscationCommand'

Same issue (dropbox listener).

**Comment by xorrior** [comment] 2017-10-07 06:38
I'll look into this.

**Comment by xorrior** [comment] 2017-10-08 01:50
@paleos @PoSHMagiC0de @nkokhi So this problem is due to an issue with Invoke-Obfuscation, not empire. You can reproduce this by using 'Launcher\\CMD\\6' as the command string in the standalone Invoke-Obfuscation powershell module. Any launcher command that includes -WindowStyle Hidden will not be recognized by powershell once obfuscated. Not sure why. I would start opening an issue [here](https://github.com/danielbohannon/Invoke-Obfuscation). Any Launcher command without the WindowStyle Hidden option will work. @PoSHMagiC0de I pushed a fix to the dev branch to alleviate the specific problem you were having. Let me know if it still is an issue.

**Closed by xorrior** 2017-10-08 01:50 UTC

**Comment by paleos** [comment] 2017-10-11 09:47
Hi xorrior,

thanks for info. I have a few questions:
**1) '-WindowStyle Hidden' option**
Is it possible to add a new parametr in usestager module to control using of '-WindowStyle Hidden' parameter?
**2) Issue in "Invoke-Obfuscation"**
Did you opened the issue there? Which number?
**3) Error "Windows cannot find 'cMd/C'"**
When I try to run obfuscated BAT, there is following Windows popup error:
"Windows cannot find 'cMd/C'. Make sure you type the name correctly, and then try again."

thanks
paleos

**Comment by honeyfairy** [comment] 2017-12-18 21:29
> Hi xorrior,
> 
> thanks for info. I have a few questions:
> 1) '-WindowStyle Hidden' option
> Is it possible to add a new parametr in usestager module to control using of '-WindowStyle Hidden' parameter?
> 2) Issue in "Invoke-Obfuscation"
> Did you opened the issue there? Which number?
> 3) Error "Windows cannot find 'cMd/C'"
> When I try to run obfuscated BAT, there is following Windows popup error:
> "Windows cannot find 'cMd/C'. Make sure you type the name correctly, and then try again."
> 
> thanks
> paleos


Any updates on the above? I am experiencing #3
