### ISSUE TITLE
Obfuscation not returning a shell.

### ISSUE THREAD

**Issue by Bry-fi** [EmpireProject/Empire#841] opened 2017-11-29 23:03 UTC
## Empire Version
 Latest
## OS Information (Linux flavor, Python version)
Kali linux and I possess both python2.7 and python3 on my box.

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

The obfuscated command returns a shell and bypasses AV. No errors are returned

## Screenshot of error, embedded text output, or Pastebin link to the error
There is no error I launch the obfuscated command on the victim machine and I don't receive an agent.

## Any additional information
Powershell is installed correctly. Both multi/launcher and windows/launcher_bat are affected by this.

**Comment by leperjulien** [comment] 2017-12-03 08:36
I faced the same issue and i think for me it was beacause of the Powershell version present on the target host (Windows 7 Starter has only powhershell v1) so the obfuscated launcher doesn't work i had to use regular launch_bat stager.

Also i forwarded port 4444 , 5555 and 8000 on my router and created 3 listeners with thoses port and only the 5555 works, others won't let any agents connect back.. but i guess the issue is on the router side probably :/

**Comment by xorrior** [comment] 2017-12-04 04:06
@Bry-fi There are so many factors that could be the root cause of you not receiving an agent. There isn't much help I can provide without a substantial amount of detail. I will say that obfuscated launchers were fixed in #826. If you can re-produce this after a fresh git pull, please run empire with the --debug 2 flag and post the output here after executing an obfuscated launcher.

**Closed by xorrior** 2017-12-04 04:06 UTC
