### ISSUE TITLE
Is this project Dead?!? Error when trying to run empire on updated Kali Linux

### ISSUE THREAD

**Issue by usmarine2141** [EmpireProject/Empire#1275] opened 2018-11-20 17:24 UTC
## Empire Version
Master Branch

## OS Information (Linux flavor, Python version)
Kali Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When running ./empire it should run empire, however i get an error (see paste below)

## Screenshot of error, embedded text output, or Pastebin link to the error
https://pastebin.com/UDxRbS6i

Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/home/god/Desktop/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

## Any additional information

I have copied the install.sh new file that was created from 1268 and ran it before installing, however still will not run.

Kali was fully updated before installing, I also tested on fresh download of 2018.4 version before updates and it worked properly.

**Comment by mr64bit** [comment] 2018-11-21 15:13
That error is normally caused by a missing or corrupt database. If `data/empire.db` exists, back it up, then run `setup/reset.sh`.

**Comment by mr64bit** [comment] 2018-11-21 17:11
Try pulling from `dev`, I just merged a PR to fix installs on Kali latest.

**Comment by usmarine2141** [comment] 2018-11-21 18:21
what is the process of pulling from a diff branch? Im not familiar with using git that  much. i know git clone and git pull thats about it. 

Is this project no longer being maintained/updated anymore?

**Comment by usmarine2141** [comment] 2018-11-21 19:14
i got it all working again. Thank you!

**Closed** 2018-11-21 19:18 UTC
