### ISSUE TITLE
Listener behind NAT - Agent switch from public Ip adress to private

### ISSUE THREAD

**Issue by qbiguenet** [EmpireProject/Empire#825] opened 2017-11-16 15:12 UTC
Hi,

I have two listeners :
![image](https://user-images.githubusercontent.com/9715259/32898111-8fb07d60-cae7-11e7-8889-f6457b44ac10.png)
(Same default profile, staging key etc..)

When i generate a stager based on the http_foreign listener, and execute it, i got a connexion on my listener and agent is deployed.

![image](https://user-images.githubusercontent.com/9715259/32898380-475a6b88-cae8-11e7-9927-416bbca4f891.png)

The problem is that I can't interract with my agents after that.
When i checked with wireshark, i noticed that my agent try now to connect to the private ip adresse (defined in the listener pub5)... 

![image](https://user-images.githubusercontent.com/9715259/32897844-eb57ae3c-cae6-11e7-8ff5-c94fa7f86d2b.png)

It seems my agent settings are updated with the settings of the "real" listener after initialization.
Is there any way to avoid that ?

Thanks a lot :-)

**Comment by jetsecurity** [comment] 2017-11-29 21:20
Hi,

Instead of 2 listeners, it would be preferable to be able to use a single listener, with the Host option pointing to the public IP and port, and with the BindIP and Port options set to the private (behind NAT and port forwarding) values:

(Empire: listeners/http) > set Host http://publicIP:publicPort
(Empire: listeners/http) > set BindIP privateIP
(Empire: listeners/http) > set Port privatePort

However, this is not currently possible because setting the Host option automatically modifies the Port option, and vice versa.

Commit https://github.com/jetsecurity/Empire/commit/cb1cb96306cfb2b44eebf29470a37aec840d84ad is a quick fix allowing to set distinct port values in the Host and Port options:

Nevertheless, I suppose some things still need to be sorted out before a clean fix:
1) Changing the settings behavior might disturb existing users. Maybe setting the Port option to a default empty value might help. This way, the Port option would still be automatically updated when the Host option is set.
2) Should the Port option be renamed BindPort for clarity?
3) The listeners code will still overwrite the Host option if BindIP is an IPv6 address (see https://github.com/jetsecurity/Empire/blob/b8cda099ce4856044d8dc4c61dd85400d7314505/lib/listeners/http.py#L271-L280 for example).

PS: Using 2 listeners doesn't work because the agent is eventually updated with the in use listener options, thus configuring the agent with the private IP addres:https://github.com/EmpireProject/Empire/blob/b8cda099ce4856044d8dc4c61dd85400d7314505/lib/listeners/http.py#L942-L950

**Comment by xorrior** [comment] 2017-11-30 17:25
@jetsecurity Thanks for the PR. @qbiguenet I will try to address this soon.

**Comment by xorrior** [comment] 2017-12-05 07:36
@jetsecurity  So I tried to reproduce this issue by using socat in front of an Empire server. Setting the BindIP to the Empire server and the host option to the external redirector. I did not experience any issues with staging or executing commands. @jetsecurity can you test this again?

**Comment by jetsecurity** [comment] 2017-12-05 21:38
The problem only occurs if you want (or have) to use a different listening port than the public port. Notably, if you are behind port forwarding with a public port different than the port Empire listens on. I suspect https://github.com/EmpireProject/Empire/issues/842 is also the same issue.

Let's say you have this port forwarding setup: publicIP:443 -> privateIP:1234. It should be possible to do:

(Empire: listeners/http) > set Host http://publicIP:443
(Empire: listeners/http) > set BindIP privateIP
(Empire: listeners/http) > set Port 1234

Empire would listen on privateIP:1234 while the agent would try to connect to publicIP:443.

However, setting the Port option automatically updates the Host option, resulting in Host being equal to http://publicIP:1234. Same thing the other way.

As a workaround, @qbiguenet tried to use two different listeners: one with the public IP and port, just to setup the agent, and one with the private IP and port which is actually listening. This solution didn't work because, at the end of the staging process, the agent is updated with the configuration of the listener it is connected to (consequently, with the private IP and port, and of course the agent doesn't know the private IP).

So it should be possible to use only one listener, but to not automatically update the port value in the Host option when a user sets the Port option (and to not automatically update the Port option when setting the Host option). That's what jetsecurity/Empire@cb1cb96 proposes.

However, as mentioned, this new behavior might disturb previous users which were used to only set the Host option, with Empire automatically setting the BindIP and Port options accordingly.

In addition, it might be a good idea to rename the Port option to BindPort for clarity. Thus, the Host option would be clearly dedicated to public connection details, while the BindIP and BindPort options would determine on which local IP and port Empire really listens.

**Comment by xorrior** [comment] 2017-12-05 23:04
@qbiguenet @jetsecurity so take a look at this issue: #363 and #482. Specifically I would recommend trying the steps I outlined in 363. If you use a http_foreign listener as well as a http listener, with different ports, the agent should still stage and operate normally. I'll test out your PR later this evening @jetsecurity. Thanks

**Comment by jetsecurity** [comment] 2017-12-06 23:14
Steps in #363 seems to be what @qbiguenet tried. In his first screenshot we can see he's using a foreign http listener with the public IP and port, and and a regular http listener with the local IP and port.

However, he experienced what seems to be the same issue as in #482: at first, the agent is able to connect back (so the listener reports a new connection), but at the end of the staging process, the agent is updated with the configuration of the listener that actually received the connection (the regular http listener configured with the local IP and port).

It should be noted that the 2.0_beta branch was merged between the working steps provided on April 6, and the issue #482 on April 9. So I suppose the big changes in 2.0_beta made impossible to use the steps provided in issue #363.

More precisely, the issue seems to come from the following code:

First, even if the agent is setup with the foreign listener, the line below sets listenerOptions to the listener which is really in use, so the regular http listener which actually received the connection:
https://github.com/EmpireProject/Empire/blob/b8cda099ce4856044d8dc4c61dd85400d7314505/lib/listeners/http.py#L191

Second, at the end of the staging process, the agent configuration is updated with these listenerOptions:
https://github.com/EmpireProject/Empire/blob/b8cda099ce4856044d8dc4c61dd85400d7314505/lib/listeners/http.py#L947-L950

To confirm this scenario, it's possible to print the value of tempListenerOptions['Host']['Value'] before the above lines. It will print the private IP address.

That's why the agent stops communicating with the IP and port provided in the foreign listener and then tries to connect to the private IP and port provided in the regular http listener. At this stage, we can see the connection attempts to the private IP in the Wireshark capture by @qbiguenet.

**Comment by xorrior** [comment] 2017-12-08 04:05
Fixed in #847

**Closed by xorrior** 2017-12-08 04:05 UTC
